openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - url: http://api.jamma.cn/user
info:
  version: "2.0.0"
  title: jm-user-api
  description: 用户系统API
paths:
  /users/{id}:
    post:
      description: 更新用户信息
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'
    get:
      description: 获取用户信息
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}/password:
    post:
      description: 修改用户密码
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Password'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'
components:
  schemas:
    User:
      type: object
      properties:
        nick:
          type: string
          example: 'jeff'
        ext:
          type: object
      description: 用户信息
    Password:
      type: object
      properties:
        oldPassword:
          type: string
        password:
          type: object
      description: 密码信息
    Ret:
      type: object
      properties:
        ret:
          type: integer
          format: int32
          example: 1
      description: 结果信息
